//! errors generated by this library

#[derive(Copy, Clone, Debug)]
/// error type of this PCD library, implemented as enum
pub enum PCDError {
    /// error type for embedded HAL v2 OutputPin errors
    OutputPinError,
    /// error type for all SPI related troubles
    SpiError,
}

impl PCDError {
    #[inline]
    /// embed a call to an OutputPin in this function to give it proper error handling
    pub fn pin<A, E>(r: Result<A, E>) -> Result<A, PCDError> {
        r.map_err(|_| PCDError::OutputPinError)
    }

    #[inline]
    /// embed SPI activity in this function to give it proper error handling
    pub fn spi<A, E>(r: Result<A, E>) -> Result<A, PCDError> {
        r.map_err(|_| PCDError::SpiError)
    }
}
