//! Errors generated by this library

#[derive(Copy, Clone, Debug)]
pub enum PCDError {
    OutputPinError,
    SpiError,
}

impl PCDError {
    #[inline]
    pub fn pin<A, E>(r: Result<A, E>) -> Result<A, PCDError> {
        r.map_err(|_| PCDError::OutputPinError)
    }

    #[inline]
    pub fn spi<A, E>(r: Result<A, E>) -> Result<A, PCDError> {
        r.map_err(|_| PCDError::SpiError)
    }
}
